// 特色手工
export const handmadeList = [
  // 手工
  {
    id: 2201,
    name: "尧坝油纸伞",
    star: 4,
    price: 100,
    oldPrice: 120,
    description: "这是尧坝油纸伞这是尧坝油纸伞这是尧坝油纸伞",
    count: 99,
    category: {
      color: ["黑色", "红色"],
    },
    img_preview: require("@/assets/upload/handmade1.webp"),
    img_list: [
      require("@/assets/upload/handmade1.webp"),
      require("@/assets/upload/handmade1.webp"),
      require("@/assets/upload/handmade1.webp"),
      require("@/assets/upload/handmade1.webp"),
      require("@/assets/upload/handmade1.webp"),
    ],
  },
  {
    id: 2202,
    name: "尧坝草鞋",
    star: 3,
    price: 20,
    oldPrice: 30,
    description: "这是尧坝草鞋这是尧坝草鞋这是尧坝草鞋",
    count: 99,
    img_preview: require("@/assets/upload/handmade2.jpeg"),
  },
  {
    id: 2203,
    name: "尧坝油纸伞",
    star: 4,
    price: 100,
    oldPrice: 120,
    description: "这是尧坝油纸伞这是尧坝油纸伞这是尧坝油纸伞",
    count: 99,
    img_preview: require("@/assets/upload/handmade1.webp"),
  },
  {
    id: 2204,
    name: "尧坝油纸伞",
    star: 5,
    price: 100,
    oldPrice: 120,
    description: "这是尧坝油纸伞这是尧坝油纸伞这是尧坝油纸伞",
    count: 99,
    img_preview: require("@/assets/upload/handmade1.webp"),
  },
  {
    id: 2205,
    name: "尧坝油纸伞",
    star: 5,
    price: 100,
    oldPrice: 120,
    description: "这是尧坝油纸伞这是尧坝油纸伞这是尧坝油纸伞",
    count: 99,
    img_preview: require("@/assets/upload/handmade1.webp"),
  },
  {
    id: 2206,
    name: "尧坝油纸伞",
    star: 5,
    price: 100,
    oldPrice: 120,
    description: "这是尧坝油纸伞这是尧坝油纸伞这是尧坝油纸伞",
    count: 99,
    img_preview: require("@/assets/upload/handmade1.webp"),
  },
]
