export const commentListData = [
  {
    id: 0,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "很好哈哈哈",
    pub_date: "2022/10/6 18:29:59",
    like: 518,
    dislike: 0,
    replay: [
      {
        user_id: 0,
        user_name: "管理员",
        text: "您的评论我们已经收到",
        pub_date: "2022/10/7 12:45:32",
      },
    ],
  },
  {
    id: 1,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "值得一去",
    pub_date: "2022/10/6 18:29:59",
    like: 509,
    dislike: 0,
    replay: [],
  },
  {
    id: 2,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "想去看看",
    pub_date: "2022/10/6 18:29:59",
    like: 7509,
    dislike: 0,
    replay: [],
  },
  {
    id: 3,

    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "想去看看",
    pub_date: "2022/10/6 18:29:59",
    like: 34,
    replay: [],
    dislike: 0,
  },
  {
    id: 4,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "1111111111",
    pub_date: "2022/10/6 18:29:59",
    like: 12,
    replay: [],
    dislike: 0,
  },
  {
    id: 5,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "什么时候能出去",
    pub_date: "2022/10/6 18:29:59",
    like: 667,
    replay: [],
    dislike: 0,
  },
  {
    id: 6,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "沙发",
    pub_date: "2022/10/6 18:29:59",
    like: 3,
    replay: [],
    dislike: 0,
  },
  {
    id: 7,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "沙发",
    pub_date: "2022/10/6 18:29:59",
    replay: [],
    like: 3,
    dislike: 0,
  },
  {
    id: 8,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "沙发",
    pub_date: "2022/10/6 18:29:59",
    like: 3,
    replay: [],
    dislike: 0,
  },
  {
    id: 9,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "沙发",
    pub_date: "2022/10/6 18:29:59",
    like: 3,
    replay: [],
    dislike: 0,
  },
  {
    id: 10,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "沙发",
    pub_date: "2022/10/6 18:29:59",
    like: 3,
    replay: [],
    dislike: 0,
  },
  {
    id: 11,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "沙发",
    pub_date: "2022/10/6 18:29:59",
    like: 3,
    replay: [],
    dislike: 0,
  },
  {
    id: 12,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "沙发",
    pub_date: "2022/10/6 18:29:59",
    like: 3,
    replay: [],
    dislike: 0,
  },
  {
    id: 13,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "沙发",
    pub_date: "2022/10/6 18:29:59",
    like: 3,
    replay: [],
    dislike: 0,
  },
  {
    id: 14,
    user_id: 9,
    user_name: "东北大喵",
    user_pic: require("@/assets/avatar.jpg"),
    text: "沙发",
    pub_date: "2022/10/6 18:29:59",
    like: 3,
    replay: [],
    dislike: 0,
  },
]
